import type {
  HtmlBreadcrumbEntry,
  HtmlPageTemplateInput,
} from '../../../@types/html.js';
import type { Runtime } from '../../../@types/reporters.js';
import type { Metric, RowMetrics } from '../../../@types/text.js';
import type {
  WatermarkLevel,
  WatermarkMetric,
  Watermarks,
} from '../../../@types/watermarks.js';
import { htmlEscape } from '../../../utils/html.js';
import { watermarks } from '../../../watermarks.js';
import { formatPct, pctValue, resolveDisplayPct } from '../metrics.js';
import { relativeHref } from './link-mapper.js';

export const metricReportClass = (
  resolvedWatermarks: Watermarks,
  metric: Metric,
  metricName: WatermarkMetric
): WatermarkLevel | 'empty' => {
  const percentage = pctValue(metric);
  if (percentage === null) return 'empty';

  return (
    watermarks.classForPercent(resolvedWatermarks, metricName, percentage) ??
    'empty'
  );
};

export const overallReportClass = (
  resolvedWatermarks: Watermarks,
  metrics: RowMetrics
): WatermarkLevel | 'empty' =>
  metricReportClass(resolvedWatermarks, metrics.statements, 'statements');

const metricBlock = (
  label: string,
  metric: Metric,
  runtime: Runtime,
  metricName: WatermarkMetric
): string => {
  const percentage = pctValue(metric);
  const total = metric.total ?? 0;
  const covered = metric.hit ?? 0;

  if (percentage !== null)
    return `
        <div class='fl pad1y space-right2'>
            <span class="strong">${formatPct(percentage)}</span>
            <span class="quiet">${label}</span>
            <span class='fraction'>${covered}/${total}</span>
        </div>`;

  if (resolveDisplayPct(metric, runtime, metricName) === null)
    return `
        <div class='fl pad1y space-right2'>
            <span class="strong">-</span>
            <span class="quiet">${label}</span>
            <span class='fraction'>-</span>
        </div>`;

  return `
        <div class='fl pad1y space-right2'>
            <span class="strong">0</span>
            <span class="quiet">${label}</span>
            <span class='fraction'>${covered}/${total}</span>
        </div>`;
};

const buildBreadcrumb = (
  pagePath: string,
  breadcrumb: readonly HtmlBreadcrumbEntry[],
  currentLabel: string,
  backBreadcrumb: boolean
): string => {
  if (backBreadcrumb)
    return `<a href="javascript:history.back()">Back</a> ${htmlEscape(currentLabel)}`;

  if (breadcrumb.length === 0) return 'All files';

  const links = breadcrumb.map(
    (breadcrumbEntry) =>
      `<a href="${htmlEscape(relativeHref(pagePath, breadcrumbEntry.pagePath))}">${htmlEscape(breadcrumbEntry.label)}</a>`
  );

  return `${links.join(' / ')} ${htmlEscape(currentLabel)}`;
};

export const renderHeader = (input: HtmlPageTemplateInput): string => {
  const assetLink = (filename: string): string =>
    htmlEscape(relativeHref(input.pagePath, filename));

  return `<!doctype html>
<html lang="en">
<head>
    <title>Code coverage report for ${htmlEscape(input.title)}</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="${assetLink('prettify.css')}" />
    <link rel="stylesheet" href="${assetLink('base.css')}" />
    <link rel="shortcut icon" type="image/x-icon" href="${assetLink('favicon.png')}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type='text/css'>
        .coverage-summary .sorter {
            background-image: url(${assetLink('sort-arrow-sprite.png')});
        }
    </style>
</head>
<body>
<div class='wrapper'>
    <div class='pad1'>
        <h1>${buildBreadcrumb(input.pagePath, input.breadcrumb, input.currentLabel, input.backBreadcrumb === true)}</h1>
        <div class='clearfix'>${metricBlock('Statements', input.metrics.statements, input.runtime, 'statements')}${metricBlock('Branches', input.metrics.branches, input.runtime, 'branches')}${metricBlock('Functions', input.metrics.functions, input.runtime, 'functions')}${metricBlock('Lines', input.metrics.lines, input.runtime, 'lines')}
        </div>
        <p class="quiet">
            Press <em>n</em> or <em>j</em> to go to the next uncovered block, <em>b</em>, <em>p</em> or <em>k</em> for the previous block.
        </p>
        <template id="filterTemplate">
            <div class="quiet">
                Filter:
                <input type="search" id="fileSearch">
            </div>
        </template>
    </div>
    <div class='status-line ${input.reportClass}'></div>
`;
};

export const renderFooter = (input: HtmlPageTemplateInput): string => {
  const assetLink = (filename: string): string =>
    htmlEscape(relativeHref(input.pagePath, filename));

  return `
                <div class='push'></div>
            </div>
            <div class='footer quiet pad2 space-top1 center small'>
                Code coverage generated by
                <a href="https://github.com/pokujs/coverage" target="_blank" rel="noopener noreferrer">@pokujs/coverage</a>
                at ${htmlEscape(input.datetime)}
            </div>
        <script src="${assetLink('prettify.js')}"></script>
        <script>
            window.onload = function () {
                prettyPrint();
            };
        </script>
        <script src="${assetLink('sorter.js')}"></script>
        <script src="${assetLink('block-navigation.js')}"></script>
    </body>
</html>
`;
};
